version: '3.8'

services:

  stihi-front:
    build:
      context: .
      dockerfile: ./Dockerfile
    #network_mode: host
    restart: always
    ports:
    - "4200:4200"
    command: ["npm","start"]

  nginx:
    image: nginx:1.19.1-perl
    #network_mode: host
    restart: always
    ports:
    - "80:80"
    depends_on:
      - stihi-front
    volumes:
      - ./build/nginx-default.conf:/etc/nginx/conf.d/default.conf
      - ./build:/var/www/stihi.io/public

networks:
  default:
